## Machine Learning Zoomcamp

### Introduction to NumPy

Contents:

- [Creating arrays](#Creating-arrays)
- [Multi-dimensional arrays](#Multi-dimensional-arrays)
- [Randomly generated arrays](#Randomly-generated-arrays)
- [Element-wise operations](#Element-wise-operations)
  - [Comparison operations](#Comparison-operations)
  - [Logical operations](#Logical-operations)
- [Summarizing operations](#Summarizing-operations)

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Dell\\anaconda3\\envs\\ml-zoomcamp\\lib\\site-packages\\numpy\\__init__.py'>

### Creating arrays

In [3]:
np.zeros(10) #generates a 1-dimensional (1-d) array of 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10) #generates a 1-d array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5) #generates a 1-d array of 10 user-defined values eg 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12]) #generating 1-d array from a list

In [8]:
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2] #accessing elements of array

3

In [11]:
np.arange(3,10) #similar to range() in Python, creates an array of specified range 3 inclusive 10 exclusive

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,100,11) #generates a 1-d array of 11 elements by dividing the space between 0 to 100 in 11 equal parts

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional arrays

In [14]:
np.zeros((5,2)) #generates a 2-d array of zeroes with 5 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) #generates a 2-d array from a list of lists

In [16]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[0,1] = 20 #item reassignment
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[2] = [1,1,1] #row reassignment
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [21]:
n[:,2] = [0,1,2] #column reassignment
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [27]:
np.random.seed(2)
np.random.rand(5,2)*100 # 2-d array of random numbers from uniform distribution

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
np.random.seed(2)
np.random.randn(5,2) #2-d array of random numbers from normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2)) # 2-d array of random integers from 0 to 100

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b = (10 + (a*2)) **2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [34]:
a/b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [36]:
a/b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

#### Comparison operations

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a > b

array([False, False,  True,  True,  True])

In [41]:
a[a > b]

array([2, 3, 4])

#### Logical operations

### Summarizing operations

In [42]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.mean() #outputs the mean of values in array

2.0

In [43]:
a.std() #outputs the standard deviation of values in array

1.4142135623730951

In [44]:
a.max() #outputs the maximum value in array

4

In [45]:
a.min() #outputs the minimum value in array

0